### ISSUE TITLE
Request :)

### ISSUE THREAD

**Issue by SkOODaT** [blaulan/PokemonGo-Slack#1]
I'm watching you create this and it looks awesome :) any chance you can add an option to get the current location of the user like pokemap does when your mobile so it updates your "poi": something that may can be toggled so if you want it on you can... 

thanks

**Comment by blaulan** [comment]
I'm searching for a good way to do this. You need an interface to continuously update the current location. Or we can use services such as Apple Find My iPhone or Google Map Location History.

**Comment by blaulan** [comment]
I achieved this by adding a webhook notification from PokemonGo-Map every time the user has changed the location. You can checkout [this pull request](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2728) for details.

**Comment by SkOODaT** [comment]
Don't know if you've ever seen this but theirs also https://www.traccar.org/client/ but getting the data directly from pogo map is prolly better

**Comment by SkOODaT** [comment]
I'm also wondering about time stamps you have it set to date time utcnow I was trying to figure out how to have it show the local time datetime.now but couldn't any chance a local time stamp could be added :)

**Comment by blaulan** [comment]
It's an issue of PokemonGo-Map, check [this pull request](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2637). I manually added a offset in `pkmn_time`, you can change that value based on your time zone.

**Comment by SkOODaT** [comment]
Awesome for pointing me in the right direction thank you again
